repos:
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.7.2
    hooks:
      - id: shellcheck
  #       args: ["--severity=warning"]  # Optionally only show errors and warnings

  # https://opencomputinglab.github.io/educational-jupyter-notebook-qa-automation/pre-commit-framework.html#example-markdownlint-pre-commit-action
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.30.0
    hooks:
      - id: markdownlint
        args:
          [
            "--disable=MD013",
            "--disable=MD047"
          ]
