# This is the configuration used to check the rubocop source code.

# https://gist.github.com/stungeye/10423491

#inherit_from: .rubocop_todo.yml
require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

Style/Encoding:
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/InlineComment:
  Description: 'Avoid inline comments.'
  Enabled: false

Layout/LineLength:
  Description: 'Limit lines to 100 characters. (Default is 80)'
  Max: 100

# Naming

Naming/ConstantName:
  Enabled: true

Naming/MethodName:
  Enabled: true

Naming/VariableName:
  Enabled: true

Naming/VariableNumber:
  Enabled: true

Naming/PredicateName:
  # Method define macros for dynamically generated method.
  MethodDefinitionMacros:
    - define_method
    - define_singleton_method
    - def_node_matcher
    - def_node_search
