# Site settings
#title: Your awesome title
#email: your-email@domain.com
#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll





# the base hostname & protocol for your site
baseurl: ''
url: 'https://soprun.com'
lang: 'ru'

title: 'Soprun Vladislav'
description: >
  Hi, welcome to my tech blog!
  <br>
  I am a Technical Architect in Like Центр.

#description: "I'm John Doe a web developer and software engineer. I studied computer science and software engineering."
#description: 'Мои личные мысли о вебе и программировании.'
#description: 'My personal thoughts on the web and programming.'

# Handling Reading
safe: true

include:
  - assets
  - favicon.ico
  - _headers

exclude:
  - .idea/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - _site/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - README.md
  - SECURITY.md
  - Makefile

keep_files: [ .git, _headers ]
timezone: "Europe/Moscow"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: true

sass:
  style: compressed

liquid:
  error_mode: strict
  strict_variables: false
  strict_filters: true

# Markdown Processors
markdown: kramdown
highlighter: rouge
render_with_liquid: false

kramdown:
  input: GFM
  auto_ids: true
  math_engine: mathjax
  hard_wrap: true
  syntax_highlighter: rouge

#  entity_output: as_char
#  toc_levels: [ 1, 2, 3, 4, 5, 6 ]
#  smart_quotes: lsquo,rsquo,ldquo,rdquo
#  input: GFM
#  hard_wrap: false
#  footnote_nr: 1

# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#plugins
plugins:
  - jekyll-dotenv
  - jekyll-environment-variables
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate

# https://jekyllrb.com/docs/configuration/front-matter-defaults/
collections:
  posts:
    output: true

defaults:
  - scope:
      path: 'assets/img'
    values:
      image: true
  - scope:
      path: '_posts'
      type: 'posts'
    values:
      layout: 'post'
      permalink: "/page/:id"
      thumbnail_default: 'https://via.placeholder.com/300x220'
      thumbnail_default_cover: 'https://via.placeholder.com/1300x300'
  - scope:
      # an empty string here means all files in the project
      path: ''
    values:
      layout: 'default'
#      author:
#        name: 'Soprun Vladislav'
#        url: 'https://soprun.com'
#        email: 'mail@soprun.com'
#        phone: '+79017972126'
#        gpg_public_key: 'https://github.com/soprun.gpg'
#        gpg_fingerprint: 'B750 2F96 C5DC 44C2'

paginate: 4
paginate_path: "/page/:num"

webrick:
  headers:
    Access-Control-Allow-Origin: "*.embednotion.com"
    Content-Security-Policy: "
      base-uri 'self';
      default-src 'self' data: ws: localhost:35729 cdnjs.cloudflare.com;
      child-src 'none';
      form-action 'self';
      connect-src 'self' ws: *.sentry.io cdnjs.cloudflare.com cloudflareinsights.com fonts.googleapis.com fonts.gstatic.com mc.yandex.ru sentry.io;
      object-src 'none';
      font-src cdnjs.cloudflare.com fonts.googleapis.com fonts.gstatic.com embednotion.com v1.embednotion.com;
      style-src 'self' fonts.googleapis.com cdnjs.cloudflare.com;
      script-src 'self' 'unsafe-inline' localhost:35729 *.sentry.io cdnjs.cloudflare.com browser.sentry-cdn.com js.sentry-cdn.com mc.yandex.ru static.cloudflareinsights.com;
      media-src *;
      img-src 'self' data: cdnjs.cloudflare.com fonts.gstatic.com images.unsplash.com via.placeholder.com dummyimage.com;
      frame-src 'self' v1.embednotion.com;
      report-uri https://o364305.ingest.sentry.io/api/6291966/security/?sentry_key=5943bcec0a2e4787882cbb988fd0aabc;
      "
