# Site settings
baseurl: ''
lang: ru
url: https://soprun.com
encoding: UTF-8

#title: Soprun Vladislav
#description: My personal thoughts on the web and programming...
#description: All about me and my blog...
#description: A description about my blog homepage
#logo: https://en.gravatar.com/userimage/94486295/9c5134e6564f702cf90ad9dbe637e046.png?size=400

title: 'Solutions Architect @soprun'
short_title: 'soprun.com'

description: >- # this means to ignore newlines until "baseurl:"
  Меня зовут Владислав, и за 10 лет я прошел путь от junior backend разработчика до Solutions Architect
  Помогу тебе или твоему сотруднику быстро и результативно прокачать навыки.

keywords: [IT Наставник, Наставничество IT, Ментор IT, Менторство, Guide, Tutorials]
#logo: https://en.gravatar.com/userimage/94486295/9c5134e6564f702cf90ad9dbe637e046.png?size=400
#logo: https://avatars.githubusercontent.com/soprun?size=400
#logo: https://github.com/soprun.png?size=400
#logo: https://images.unsplash.com/photo-1488722796624-0aa6f1bb6399?w=400&fit=crop&fm=webp&auto=compress
logo: /assets/img/avatar-small.png
email: mail@soprun.com

author:
  name: Soprun Vladislav
  first_name: Vladislav
  last_name: Soprun
  nickname: soprun
  description: >-
    Меня зовут Владислав, и за 10 лет я прошел путь от junior backend разработчика до Solutions Architect.<br><br>
    Помогу тебе или твоему сотруднику быстро и результативно прокачать навыки.
  url: https://soprun.com
  email: mail@soprun.com
  phone: +79017972126
  avatar: /assets/img/avatar-small.png
  gpg_public_key: https://github.com/soprun.gpg
  gpg_fingerprint: B750 2F96 C5DC 44C2

color:
  theme: '#ffffff'
  background: '#ffffff'
  text: '#000000'
  primary: '#cfc3ee'
  secondary: '#cfc3ee'
  tile_color: '#ffffff'

# Handling Reading
safe: false

include:
  - CNAME
  - assets
  - favicon.ico
  - _headers
  - robots.txt
  - robots.txt.asc

exclude:
  - .editorconfig
  - .env
  - .git
  - .gitattributes
  - .gitignore
  - .idea/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - _site/
  - report/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - README.md
  - SECURITY.md
  - Makefile
  - .DS_STORE

keep_files: [ .git, _headers ]
timezone: "Europe/Moscow"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: true

sass:
  style: compressed

liquid:
  error_mode: strict
  strict_variables: false
  strict_filters: true

# Markdown Processors
markdown: kramdown
highlighter: rouge
render_with_liquid: false

#  https://jekyllrb.com/docs/configuration/markdown/#syntax-highlighting-coderay
kramdown:
  input: GFM
  auto_ids: true
  math_engine: mathjax
  hard_wrap: true
  syntax_highlighter: rouge
  entity_output: as_char
  footnote_nr: 1
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#plugins
plugins:
  - jekyll-dotenv
  - jekyll-environment-variables
  #  - jekyll-feed
  #  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-notion

# https://jekyllrb.com/docs/configuration/front-matter-defaults/
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:name
  
#  posts:
#    output: true
#    permalink: /:collection/:name
#  pages:
#    output: true
#    permalink: /:collection/:name
#  category:
#    output: true
#    permalink: /:collection/:name

#notion:
#  fetch_on_watch: true
#  databases:
#    - id: 412f963c1eb740cd88932a406d9380b8
#      data: notes
#    - id: b35a3080619745ad9a9ae2478c109299
#      data: skills

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: page
      type: page
      noindex: false
      paginate: false
      published: true
      author:
        name: ~
        url: ~
        email: ~
        avatar: ~
      image: https://images.unsplash.com/photo-1488722796624-0aa6f1bb6399?w=400&fit=crop&fm=webp&auto=compress
      categories: []

  - scope:
      type: posts
      path: _posts
    values:
      layout: post
      type: post
#      permalink: '/page/:id'
#      permalink: /:categories/:title:output_ext
      permalink: /:slug

#  - scope:
#      type: pages
#      path: _pages
#    values:
#      layout: page

  - scope:
      path: 'assets/img'
    values:
      image: true

# https://www.digitalocean.com/community/tutorials/how-to-control-urls-and-links-in-jekyll
#permalink: date
# https://mademistakes.com/mastering-jekyll/how-to-link/#collection-url-defaults
#permalink: /:collection/:path
permalink: /:categories/:title
paginate: 5
paginate_path: /page/:num

page_excerpts: true

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50
excerpt_separator: "<!--more-->"
excerpt_delimiter: ---
