# Site settings
#title: Your awesome title
#email: your-email@domain.com
#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll





# Where things are
#source: .
#destination: ./public

# the base hostname & protocol for your site
# baseurl: /
# url: "{{ site.env.APP_URL }}"
# lang: "{{ site.env.APP_URL }}"
# lang: ru

name: "Soprun Vladislav"
email: "mail@soprun.com"
phone: "+79017972126"

#google_analytics: 'UA-162879780-1'
#google_gtag: 'UA-162879780-1'
#google_tag_manager: 'GTM-K3KVG8Z'

title: 'Soprun Vladislav'
description: 'Hi, welcome to my tech blog! <br>I am a Technical Architect in Moscow.'
#description: 'Мои личные мысли о вебе и программировании.'
#description: 'My personal thoughts on the web and programming.'

author:
  name: "Soprun Vladislav"
  url: "https://soprun.com"

# Copy link to profile
public_links:
  medium: "https://medium.com/@soprun"
  github: "https://github.com/soprun"
  gitlab: "https://gitlab.com/soprun"

# Handling Reading
safe: true

include:
  - assets
  - favicon.ico

exclude:
  - .idea/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - _site/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - README.md
  - SECURITY.md
  - Makefile

keep_files: [ '.git' ]
timezone: "Europe/Moscow"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: true

sass:
  style: compressed

liquid:
  error_mode: strict
  strict_variables: false
  strict_filters: true

# Markdown Processors
markdown: kramdown
kramdown:
  auto_ids: true
  math_engine: mathjax
  syntax_highlighter: rouge

#  entity_output: as_char
#  toc_levels: [ 1, 2, 3, 4, 5, 6 ]
#  smart_quotes: lsquo,rsquo,ldquo,rdquo
#  input: GFM
#  hard_wrap: false
#  footnote_nr: 1

# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#plugins
plugins:
  - jekyll-dotenv
  - jekyll-environment-variables
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate

defaults:
  - scope:
      path: 'assets/img'
    values:
      image: true
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"


paginate: 4
paginate_path: "/page/:num"
