# the base hostname & protocol for your site
url: "https://soprun.com"
email: "mail@soprun.com"
phone: "+79017972126"
logo: "/assets/img/avatar-small.png"
gravatar: https://gravatar.com/avatar/a93d85b63901fdcdf73c6f906b86f008

#google_analytics: 'UA-162879780-1'
#google_gtag: 'UA-162879780-1'
yandex_metrika: '55435306'

title: Soprun Vladislav
# description: I am a Technical Architect at Like Центр!
description: >-
  Hi! Welcome to my blog! 👋🏻<br>
  I am a Technical Architect at <br>
  <a href="https://likecentre.ru" class="text-decoration-none" rel="noopener noreferrer" target="_blank">Like Центр</a>!

author:
  name: "Soprun Vladislav"
  url: "https://soprun.com"

# Copy link to profile
public_links:
  medium: "https://medium.com/@soprun"
  github: "https://github.com/soprun"
  gitlab: "https://gitlab.com/soprun"

gpg:
  short: 'B750 2F96 C5DC 44C2'
  fingerprint: "8120213055C84C2C3324FB08B7502F96C5DC44C2"
  mit_key_server: "https://pgp.mit.edu/pks/lookup?op=get&search=0xB7502F96C5DC44C2"

theme: "jekyll-theme-minimal"

# Handling Reading
safe: true

#permalink: /:title/

include:
  - assets
  - favicon.ico

exclude:
  - .idea/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - _site/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - README.md

keep_files: [ ".git", ".svn" ]
timezone: "Europe/Moscow"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

sass:
  style: compressed

gist:
  noscript: false

# Markdown Processors
markdown: kramdown
kramdown:
  auto_ids: true
  math_engine: mathjax
  syntax_highlighter: rouge

#  entity_output: as_char
#  toc_levels: [ 1, 2, 3, 4, 5, 6 ]
#  smart_quotes: lsquo,rsquo,ldquo,rdquo
#  input: GFM
#  hard_wrap: false
#  footnote_nr: 1


# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
#  - jekyll-github-metadata

#webrick:
#  headers:
#    Access-Control-Allow-Origin: "https://soprun.com"
#    Access-Control-Allow-Methods: "GET, OPTIONS, HEAD"
#    Vary: "Origin"
#    Content-Security-Policy: "
#    default-src 'self' https:;
#    connect-src mc.yandex.ru;
#    script-src 'self' 'unsafe-inline' mc.yandex.ru;
#    style-src 'self' 'unsafe-inline' fonts.googleapis.com;
#    font-src 'self' fonts.gstatic.com;
#    report-uri https://soprun.report-uri.com/r/d/csp/enforce;
#    "

# default-src 'self' https:;
# see report: https://report-uri.com/account/reports/csp/

#  default-src 'none';
#  script-src 'self';
#  connect-src 'self';
#  img-src 'self';
#  style-src 'self';
#  font-src 'self';

defaults:
  - scope:
      path: 'assets/img'
    values:
      image: true
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
