baseurl: ""
url: https://soprun.com
lang: ru
encoding: utf-8
timezone: "Europe/Moscow"

# Enable safe mode
safe: false
quiet: false
verbose: false
# https://jekyllrb.com/docs/configuration/incremental-regeneration/
regenerate: true
incremental: true

#title: Soprun Vladislav
#description: My personal thoughts on the web and programming...
#description: All about me and my blog...
#description: A description about my blog homepage
#logo: https://en.gravatar.com/userimage/94486295/9c5134e6564f702cf90ad9dbe637e046.png?size=400

title: 'Solution Architect @soprun'
short_title: 'soprun.com'

description: >- # this means to ignore newlines until "baseurl:"
  Меня зовут Владислав, и за 10 лет я прошел путь от junior backend разработчика до Solution Architect
  Помогу тебе или твоему сотруднику быстро и результативно прокачать навыки.
  На этом сайте я делюсь заметками и мыслями.

keywords: [ IT Наставник, Наставничество IT, Ментор IT, Менторство, Guide, Tutorials ]

#logo: https://en.gravatar.com/userimage/94486295/9c5134e6564f702cf90ad9dbe637e046.png?size=400
#logo: https://avatars.githubusercontent.com/soprun?size=400
#logo: https://github.com/soprun.png?size=400
#logo: https://images.unsplash.com/photo-1488722796624-0aa6f1bb6399?w=400&fit=crop&fm=webp&auto=compress
logo: /assets/img/avatar-small.png
logo_webp: /assets/img/avatar-small.webp

# email: mail@soprun.com

author:
  name: Soprun Vladislav
  first_name: Vladislav
  last_name: Soprun
  nickname: soprun
  gender: M
  # photo: https://gravatar.com/avatar/a93d85b63901fdcdf73c6f906b86f008
  # Hotlinking
  photo: https://soprun.com/assets/img/avatar-small.png
  photo_webp: https://soprun.com/assets/img/avatar-small.webp
  avatar: https://soprun.com/assets/img/avatar-small.png
  description: >-
    Меня зовут Владислав, и за 10 лет я прошел путь от junior backend разработчика до Solution Architect.<br><br>
    Помогу тебе или твоему сотруднику быстро и результативно прокачать навыки.
  url: https://soprun.com
  domain: soprun.com
  email: mail@soprun.com
  phone: "+79017972126"
  country: Russia
  region: Moscow
  ## криптографический открытый ключ, например, SSH или GPG
  key: ~
  site-profiles: ~
  # gpg_public_key: https://github.com/soprun.gpg
  gpg_public_key: https://keys.openpgp.org/vks/v1/by-fingerprint/8120213055C84C2C3324FB08B7502F96C5DC44C2
  gpg_fingerprint: 8120213055C84C2C3324FB08B7502F96C5DC44C2
  gpg_fingerprint_short: B7502F96C5DC44C2
  gpg_search_link: https://keys.openpgp.org/search?q=mail%40soprun.com
  birthday: 1992-11-30
  social_profile:
    - type: facebook
      username: vladislav.soprun
      value: https://www.facebook.com/vladislav.soprun
    - type: twitter
      username: VladislavSoprun
      value: https://twitter.com/VladislavSoprun
    - type: linkedin
      username: soprun
      value: https://www.linkedin.com/in/soprun/
    - type: Instagram
      username: vladislav.soprun
      value: https://www.instagram.com/vladislav.soprun
    - type: VK
      username: soprun.vladislav
      value: https://vk.com/soprun.vladislav
    - type: GitHub
      username: soprun
      icon: <i class="fa-brands fa-github" aria-hidden="true"></i>
      value: https://github.com/soprun/
    - type: GitLab
      username: soprun
      icon: <i class="fa-brands fa-gitlab" aria-hidden="true"></i>
      value: https://gitlab.com/soprun/
    #    - type: Telegram
    #      title: Telegram channel
    #      icon: <i class="fa-brands fa-telegram" aria-hidden="true"></i>
    #      value: https://t.me/+YpCP4MsEorBmN2Qy
    - type: Telegram
      username: soprun
      title: Telegram channel
      icon: <i class="fa-brands fa-telegram" aria-hidden="true"></i>
      value: https://t.me/soprun
    #    - type: Medium
    #      icon: <i class="fa-brands fa-medium" aria-hidden="true"></i>
    #      value: https://medium.com/@soprun
  urls:
    - value: https://soprun.com
      type:
        - HOME
        - pref
  org:
    name: Страна Девелопмент
    unit: Департамент ИТ-архитектуры
    role: Solution Architect
    nickname: ~
    url: https://strana.com
    photo: ~
    tz: ~
    tel: [ ]
    email: [ ]
    logo:
      value: ~
      alt: ~
    address:
      street-address: Пресненская наб., 6, стр. 2
      locality: Москва
      region: Moscow
      postal-code: 108811
      country-name: Russia
  #  address:
  #    - type: Work
  #      street-address: 1123 Main Street
  #      locality: Palo Alto
  #      region: California
  #      region-code: CA
  #      postal-code: 94301
  #      country-name: USA
  #      dom: US
  #      postal: mail
  #      parcel: shipments
  emails:
    - type:
        - INTERNET
        - HOME
        - pref
      value: mail@soprun.com
    - type:
        - INTERNET
        - WORK
      value: develop@soprun.com
    - type:
        - INTERNET
        - WORK
      value: job@soprun.com
  phones:
    - value: +7 (901) 797-21-26i
      type:
        - home
        - work
        - cell
        - pref


color:
  theme: '#ffffff'
  background: '#ffffff'
#  color_scheme: 'light'

include:
  - CNAME
  - assets
  - _headers
  - .well-known

exclude:
  - .editorconfig
  - .env
  - .env.local
  - .github
  - .gitattributes
  - .gitignore
  - .idea/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - .bundle/
  - _site/
  - functions/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - README.md
  - Makefile
  - .DS_STORE
  - Guardfile
  - Rakefile
  - HTMLProofer.rb

cache: bundler
keep_files: [ .git, _headers, .well-known ]
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

sass:
  style: compressed
  sourcemap: always
  line_comments: false

# https://jekyllrb.com/docs/configuration/liquid/
# `lax` — Игнорировать все ошибки.
# `warn` — Выводить предупреждение на консоль для каждой ошибки.(по умолчанию)
# `strict` — Вывести сообщение об ошибке и остановить сборку.
liquid:
  error_mode: warn
  strict_variables: false
  strict_filters: false

# Markdown Processors
markdown: kramdown
highlighter: rouge
render_with_liquid: false

#markdown: HTMLPipeline
html_pipeline:
  filters:
    - "markdownfilter"
    - "sanitizationfilter"
    - "emojifilter"
    - "mentionfilter"
  context:
    asset_root: "https://soprun.com/assets/"
    base_url: "https://soprun.com"

#  https://jekyllrb.com/docs/configuration/markdown/#syntax-highlighting-coderay
kramdown:
  input: GFM
  auto_ids: true
  math_engine: mathjax
  hard_wrap: true
  syntax_highlighter: rouge
  entity_output: as_char
  footnote_nr: 1
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  show_warnings: false

# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#plugins
plugins:
  - jekyll-dotenv
  - jekyll-environment-variables
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-relative-links
  #  - jekyll-feed
  #  - jekyll-sitemap

# https://jekyllrb.com/docs/configuration/front-matter-defaults/
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:name

#  posts:
#    output: true
#    permalink: /:collection/:name
#  pages:
#    output: true
#    permalink: /:collection/:name
#  category:
#    output: true
#    permalink: /:collection/:name

#notion:
#  fetch_on_watch: true
#  databases:
#    - id: 412f963c1eb740cd88932a406d9380b8
#      data: notes
#    - id: b35a3080619745ad9a9ae2478c109299
#      data: skills

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: page
      title: ~
      description: ~
      type: page
      image: /assets/img/about.jpeg
      noindex: false
      paginate: false
      published: true
      last_modified_at: ~
      tags: [ ]
      categories: [ ]

  - scope:
      type: posts
      path: _posts
    values:
      layout: post
      type: post
      #      permalink: '/page/:id'
      #      permalink: /:categories/:title:output_ext
      permalink: /:slug

  #  - scope:
  #      type: pages
  #      path: _pages
  #    values:
  #      layout: page

  - scope:
      path: 'assets/img'
    values:
      image: true

# https://www.digitalocean.com/community/tutorials/how-to-control-urls-and-links-in-jekyll
permalink: date
# https://mademistakes.com/mastering-jekyll/how-to-link/#collection-url-defaults
#permalink: /:collection/:path
#permalink: /:categories/:title
paginate: 5
paginate_path: /page/:num
page_excerpts: true

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50
excerpt_separator: "<!--more-->"
excerpt_delimiter: ---

# https://github.com/benbalter/jekyll-relative-links

#webrick:
#  headers:
#    My-Header: My-Value
#    My-Other-Header: My-Other-Value
