# Site settings
baseurl: ''
lang: 'ru'
url: 'https://soprun.com'
title: 'Soprun Vladislav'
description: >
  Hi, welcome to my tech blog!
  <br>
  I am a Technical Architect in Like Центр.

#description: "I'm John Doe a web developer and software engineer. I studied computer science and software engineering."
#description: 'Мои личные мысли о вебе и программировании.'
#description: 'My personal thoughts on the web and programming.'

# Handling Reading
safe: false
incremental: true

include:
  - assets
  - favicon.ico
  - _headers

exclude:
  - .idea/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - _site/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - README.md
  - SECURITY.md
  - Makefile

keep_files: [ .git, _headers ]
timezone: "Europe/Moscow"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: true

sass:
  style: compressed

liquid:
  error_mode: strict
  strict_variables: false
  strict_filters: true

# Markdown Processors
markdown: kramdown
highlighter: rouge
render_with_liquid: false

#  https://jekyllrb.com/docs/configuration/markdown/#syntax-highlighting-coderay
kramdown:
  input: GFM
  auto_ids: true
  math_engine: mathjax
  hard_wrap: true
  syntax_highlighter: rouge
  entity_output: as_char
  footnote_nr: 1
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#plugins
plugins:
  - jekyll-dotenv
  - jekyll-environment-variables
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-notion

# https://jekyllrb.com/docs/configuration/front-matter-defaults/
collections:
  posts:
    output: true
  default:
    output: true

notion:
  fetch_on_watch: true
  databases:
    - id: 412f963c1eb740cd88932a406d9380b8
      data: reading_list

defaults:
  - scope:
      path: 'assets/img'
    values:
      image: true
  - scope:
      path: '_posts'
      type: 'posts'
    values:
      layout: 'post'
      noindex: false
      permalink: '/page/:id'
  - scope:
      # an empty string here means all files in the project
      path: ''
      type: "default"
    values:
      layout: 'default'
      noindex: false

permalink: date
paginate: 4
paginate_path: "/page/:num"

#webrick:
#  headers:
#    Access-Control-Allow-Origin: "*"
#    Content-Security-Policy: default-src 'self' 'unsafe-inline' *;
#    Content-Security-Policy: "
#      base-uri 'self';
#      default-src 'self' data: ws: localhost:35729 cdnjs.cloudflare.com;
#      child-src 'none';
#      form-action 'self';
#      connect-src 'self' ws: *.sentry.io cdnjs.cloudflare.com cloudflareinsights.com fonts.googleapis.com fonts.gstatic.com mc.yandex.ru sentry.io;
#      object-src 'none';
#      font-src cdnjs.cloudflare.com fonts.googleapis.com fonts.gstatic.com embednotion.com v1.embednotion.com;
#      style-src 'self' fonts.googleapis.com cdnjs.cloudflare.com;
#      script-src 'self' *.sentry.io cdnjs.cloudflare.com browser.sentry-cdn.com js.sentry-cdn.com mc.yandex.ru static.cloudflareinsights.com;
#      media-src *;
#      img-src 'self' data: images.unsplash.com via.placeholder.com;
#      frame-src 'self' v1.embednotion.com;
#      "
